# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.1.1
    hooks:
      - id: fix-encoding-pragma
        args:
          - '--pragma=# coding: utf-8'
      - id: autopep8-wrapper
        language_version: python2
        args:
          - --in-place
          - --ignore=E722,E741,E501,E228,E226,E261,E266,E128,E402,E241,W503
          - --select=W504
      - id: check-added-large-files
      - id: check-ast
        language_version: python2
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --no-ensure-ascii
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-xml
      - id: debug-statements
        language_version: python2
      - id: flake8
        language_version: python2
        args:
          - --ignore=E722,E741,E501,E228,E226,E261,E266,E128,E402,W503,W605
          - --builtins=G,request
          - --jobs=1
        additional_dependencies:
          - flake8-print
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
-   repo: https://github.com/xiachufang/importanize/
    rev: 0.7.2
    hooks:
    -   id: importanize
        args: [--verbose]
        language_version: python2
-   repo: https://github.com/xiachufang/mirrors-pylint
    rev: v1.9.2
    hooks:
    -   id: pylint
        args:
          - --py3k
          - --score=n
